services:
  pgdatabase:
    image: postgres:17-alpine
    container_name: pgdatabase
    environment:
      - POSTGRES_DB=ny_taxi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - vol-pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    networks:
      - pg-network

volumes:
  vol-pgdata:
    external: true
networks:
  pg-network:
    driver: bridge
